services:
  app:
    image: ghcr.io/limekh/catty-reminders-app:latest
    container_name: catty-app
    restart: always

    ports:
      - "8181:8181"

    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: catty_db
      DB_USER: catty_user
      DB_PASSWORD: catty_password

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: catty-db
    restart: always

    environment:
      MYSQL_DATABASE: catty_db
      MYSQL_USER: catty_user
      MYSQL_PASSWORD: catty_password
      MYSQL_ROOT_PASSWORD: rootpassword

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
