name: catty

services:
  app:
    image: ghcr.io/limekh/catty-reminders-app:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8181:8181"
    volumes:
      - ./config.json:/app/config.json:ro

  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: catty_reminders
      MARIADB_USER: catty
      MARIADB_PASSWORD: cattypass
      MARIADB_ROOT_PASSWORD: rootpass

    volumes:
      - catty-db-data:/var/lib/mysql

volumes:
  catty-db-data:
